name: Geelong
favicon: null
layout_spectrum: 0.7685176394879818
typography_spectrum: 0.10734746931120753
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7400847061071545
  lightness: 0.5444216728210449
  saturation: 0.3625805154442787
  rhythmicContrast: 0.5641811022069305
purpose: []
